name: 'Karate Test Runner'
description: 'Run Karate tests on sanityTest.feature files.'
inputs:
  testDir:
    description: 'Path to the test directory.'
    required: true
    default: 'sanityTests'
  testFilePath:
    description: 'Path to the test filenames.'
    required: true
    default: 'SanityTest.feature,AnotherSanityTest.feature'
  karateVersion:
    description: 'Karate version to use.'
    required: true
    default: 'latest'
  baseUrl:
    description: 'Base URL to use.'
    required: true
  authToken:
    description: 'Authorization header to use.'
    required: false
    default: ''
  tags:
    description: 'Test-Tags to run.'
    required: false
    default: ''
  properties:
    description: 'JSON list of key/value pairs for additional configuration.'
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'index.js'
