name: Build and Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        java-distro: ['azul']
        java-version: [11,17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.java-distro }}
          java-version: ${{ matrix.java-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
